### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by eric1932** [sunsx9316/DanDanPlayForiOS#4]
master分支
已下载pod
编译时提示找不到APPKey.h
查了一下发现是友盟的SDK key
但是并不知道应该怎么配置这个文件
网上也没有搜到合适的教程

能指点一下怎么配置这个文件吗？

**Comment by eric1932** [comment]
还有是否能在GitHub上面放出编译好的版本？

**Comment by sunsx9316** [comment]
嗯 我调整一下

**Comment by eric1932** [comment]
![default](https://user-images.githubusercontent.com/10938293/52675210-ac096580-2eeb-11e9-82e2-e14bf7df5edb.png)

还是编译失败
并不能理解git-crypt的解密方法

**Comment by sunsx9316** [comment]
这是一些appkey 本身不方便暴露 master分支应该已经做了处理 还是不能编译直接移除appkey.h 然后把import的地方注释掉就ok

**Comment by eric1932** [comment]
好的谢谢
