### ISSUE TITLE
SMB無法訪問

### ISSUE THREAD

**Issue by bssxmh** [sunsx9316/DanDanPlayForiOS#5]
在兩台Ipad上皆無法訪問NAS或是windows的分享
皆報錯 Unable to connect to device

但在裝置上的文件管理器可以正常訪問SMB

以下為截圖
https://imgur.com/Sokmj0B
https://imgur.com/X8Mfm3y

**Comment by sunsx9316** [comment]
Windows需要开启smbv1，具体可以查查。如果觉得麻烦可以试试webdav。

**Comment by bssxmh** [comment]
> Windows需要开启smbv1，具体可以查查。如果觉得麻烦可以试试webdav。

在Nas上開啟samba1 support之後就可以正常連線了
感謝回覆

**Comment by wolfcon** [comment]
而且要想在 Android 电视上的 App 等发现电脑分享啥的, 都一律是 SMBv1 的锅🤣
